# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  daily_pending_summary:
    class: DailyPendingSummaryJob
    queue: default
    schedule: every day at 9am
  cleanup_pending_payments:
    class: CleanupPendingPaymentsJob
    queue: default
    schedule: every day at 3am
  sync_zoho_emails:
    class: SyncZohoEmailsJob
    queue: default
    schedule: every 30 minutes
  # sync_brevo_contacts:
  #   class: SyncBrevoContactsJob
  #   queue: default
  #   schedule: every 6 hours
  sync_brevo_newsletters:
    class: SyncBrevoNewslettersJob
    queue: default
    schedule: every monday at 8am
  # refresh_funding_opportunities:
  #   class: RefreshFundingOpportunitiesJob
  #   queue: default
  #   schedule: every monday at 9am

development:
  # refresh_funding_opportunities:
  #   class: RefreshFundingOpportunitiesJob
  #   queue: default
  #   schedule: every day at 10am
